const cuisineTypes = [
    "Afghan",
    "African",
    "American",
    "Argentine",
    "Armenian",
    "Asian Fusion",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Barbeque",
    "Basque",
    "Belgian",
    "Brasseries",
    "Brazilian",
    "Breakfast & Brunch",
    "British",
    "Buffets",
    "Bulgarian",
    "Burgers",
    "Burmese",
    "Cafes",
    "Cafeteria",
    "Cajun/Creole",
    "Cambodian",
    "Caribbean",
    "Catalan",
    "Cheesesteaks",
    "Chicken Wings",
    "Chinese",
    "Comfort Food",
    "Creperies",
    "Cuban",
    "Czech",
    "Delis",
    "Diners",
    "Ethiopian",
    "Fast Food",
    "Filipino",
    "Fish & Chips",
    "Fondue",
    "Food Court",
    "Food Stands",
    "French",
    "Gastropubs",
    "German",
    "Gluten-Free",
    "Greek",
    "Guamanian",
    "Halal",
    "Hawaiian",
    "Himalayan/Nepalese",
    "Hot Dogs",
    "Hungarian",
    "Iberian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Korean",
    "Kosher",
    "Laotian",
    "Latin American",
    "Live/Raw Food",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Modern European",
    "Mongolian",
    "Moroccan",
    "Pakistani",
    "Pan Asian",
    "Persian/Iranian",
    "Peruvian",
    "Pizza",
    "Polish",
    "Portuguese",
    "Poutineries",
    "Russian",
    "Salad",
    "Salvadoran",
    "Sandwiches",
    "Scandinavian",
    "Scottish",
    "Seafood",
    "Singaporean",
    "Slovakian",
    "Soul Food",
    "Soup",
    "Southern",
    "Spanish",
    "Sri Lankan",
    "Steakhouses",
    "Supper Clubs",
    "Sushi Bars",
    "Syrian",
    "Taiwanese",
    "Tapas Bars",
    "Tapas/Small Plates",
    "Tex-Mex",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Vegan",
    "Vegetarian",
    "Venezuelan",
    "Vietnamese",
    "Waffles",
    "Wraps"
  ];
  
  export default cuisineTypes;
